apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword }}
  REDMINE_DB_PASSWORD: {{ .Values.secrets.redmineDbPassword }}
  REDMINE_SECRET_KEY_BASE: {{ .Values.secrets.secretKeyBase }}